sudo: required
services:
  - docker

before_install:
  - docker build -t iftikharmahmood/docker-react -f Dockerfile.dev .

script:
  - docker run iftikharmahmood/docker-react npm run test -- --coverage


  